"""
Aggregate per-view metrics from re-evaluation runs and emit LaTeX table fragments
with mean ± std for Chapter 4 tables (4.2, 4.3, 4.5, 4.6–4.9, 4.10).

Usage (from TensoIR repo root after running scripts/run_primary_reeval.sh):
    python scripts/aggregate_thesis_metrics.py

Output: prints LaTeX-ready table rows to stdout. Redirect to a file or
paste directly into chapter4_Evaluation_and_Results.tex.
"""

import glob
import os
import re
import sys

import numpy as np

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LOG  = os.path.join(REPO, "log", "log_rotated_multi_lights")
RLIT = os.path.join(REPO, "relighting")


# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────

def fmt(mean, std, decimals=2):
    """Return LaTeX string  'mean ± std'  with given decimal places."""
    fmt_str = f"{{:.{decimals}f}}"
    return f"{fmt_str.format(mean)} \\pm {fmt_str.format(std)}"

def fmt4(mean, std):
    return fmt(mean, std, decimals=4)


def find_npz(run_dir):
    """Find metrics_per_view.npz inside a run directory.
    Looks in imgs_test_all/ directly, then in any test_reeval_final*/imgs_test_all/.
    Returns path or None.
    """
    # Direct path (from training loop eval)
    direct = os.path.join(run_dir, "imgs_test_all", "metrics_per_view.npz")
    if os.path.exists(direct):
        return direct

    # Path from render_only re-eval
    pattern = os.path.join(run_dir, "test_reeval_final*", "imgs_test_all", "metrics_per_view.npz")
    matches = sorted(glob.glob(pattern))
    if matches:
        return matches[-1]  # take most recent

    return None


def load_npz(run_dir, label=""):
    path = find_npz(run_dir)
    if path is None:
        print(f"  [WARN] metrics_per_view.npz not found in {run_dir}", file=sys.stderr)
        return None
    return np.load(path)


def ms(arr):
    """Return (mean, std) as floats."""
    a = np.asarray(arr, dtype=float)
    return float(np.mean(a)), float(np.std(a, ddof=0))


# ─────────────────────────────────────────────────────────────────────────────
# Relighting helpers  (parse existing per-view relight_psnr.txt files)
# ─────────────────────────────────────────────────────────────────────────────

ENV_MAPS = ["courtyard", "snow", "sunset", "bridge", "fireplace"]

def parse_relight_per_view(scene_dir):
    """Parse all test_*/relighting_without_bg/relight_psnr.txt files.
    Returns dict: {env_name: {'psnr': [], 'ssim': [], 'lpips_vgg': []}}
    Falls back to relight_metrics_per_view.npz if available.
    """
    # Prefer .npz if already generated by the patched script
    npz_path = os.path.join(scene_dir, "relight_metrics_per_view.npz")
    if os.path.exists(npz_path):
        d = np.load(npz_path)
        result = {}
        for env in ENV_MAPS:
            psnr_key = f"psnr_{env}"
            if psnr_key in d:
                result[env] = {
                    "psnr":      d[psnr_key],
                    "ssim":      d.get(f"ssim_{env}", np.array([])),
                    "lpips_vgg": d.get(f"lpips_vgg_{env}", np.array([])),
                }
        if result:
            return result

    # Parse per-view txt files
    result = {env: {"psnr": [], "ssim": [], "lpips_vgg": []} for env in ENV_MAPS}
    view_dirs = sorted(glob.glob(os.path.join(scene_dir, "test_[0-9][0-9][0-9]")))
    for vdir in view_dirs:
        txt = os.path.join(vdir, "relighting_without_bg", "relight_psnr.txt")
        if not os.path.exists(txt):
            continue
        with open(txt) as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                # Format: "courtyard: PNSR 24.19; SSIM 0.94; L_Alex 0.06; L_VGG 0.07"
                for env in ENV_MAPS:
                    if line.lower().startswith(env):
                        nums = re.findall(r"[-+]?\d*\.?\d+(?:[eE][-+]?\d+)?", line)
                        if len(nums) >= 4:
                            result[env]["psnr"].append(float(nums[0]))
                            result[env]["ssim"].append(float(nums[1]))
                            result[env]["lpips_vgg"].append(float(nums[3]))
                        break
    return result


# ─────────────────────────────────────────────────────────────────────────────
# Table 4.2 — Normal MAE
# ─────────────────────────────────────────────────────────────────────────────

def table_42():
    runs = {
        "TensoIR (paper)": None,  # single published value
        "TensoIR (local repro.)": {
            "Ficus":  os.path.join(LOG, "ficus_vanilla_rotated_baseline-20260409-102551"),
            "Hotdog": os.path.join(LOG, "hotdog_vanilla_rotated_baseline-20260409-104734"),
            "Lego":   os.path.join(LOG, "lego_vanilla_rotated_baseline-20260409-121707"),
        },
        "Unified Curriculum Pipeline": {
            "Ficus":  os.path.join(LOG, "ficus_unified_v6-20260416-014135"),
            "Hotdog": os.path.join(LOG, "hotdog_unified_v6-20260416-040838"),
            "Lego":   os.path.join(LOG, "lego_unified_v6-20260416-062047"),
        },
    }
    paper_vals = {"Ficus": 3.95, "Hotdog": 3.24, "Lego": 5.63}

    print("\n% ── Table 4.2: Normal MAE ──────────────────────────────────")
    print("% Method & Setting & Ficus MAE & Hotdog MAE & Lego MAE")
    for method, scene_dirs in runs.items():
        if scene_dirs is None:
            row = " & ".join(
                f"\\textbf{{{paper_vals[s]:.2f}}}" if False else f"{paper_vals[s]:.2f}"
                for s in ["Ficus", "Hotdog", "Lego"]
            )
            print(f"TensoIR (paper) & Rot.\\ multi & {row} \\\\")
            continue
        cells = []
        for scene in ["Ficus", "Hotdog", "Lego"]:
            d = load_npz(scene_dirs[scene])
            if d is not None and "mae" in d:
                m, s = ms(d["mae"])
                cells.append(f"${fmt(m, s)}$")
            else:
                cells.append("---")
        row = " & ".join(cells)
        short = "TensoIR (local repro.)" if "repro" in method else "Unified Curriculum Pipeline"
        print(f"{short} & Rot.\\ multi & {row} \\\\")


# ─────────────────────────────────────────────────────────────────────────────
# Table 4.3 — Albedo reconstruction
# ─────────────────────────────────────────────────────────────────────────────

def table_43():
    scene_map = {
        "repro": {
            "Ficus":  os.path.join(LOG, "ficus_vanilla_rotated_baseline-20260409-102551"),
            "Hotdog": os.path.join(LOG, "hotdog_vanilla_rotated_baseline-20260409-104734"),
            "Lego":   os.path.join(LOG, "lego_vanilla_rotated_baseline-20260409-121707"),
        },
        "unified": {
            "Ficus":  os.path.join(LOG, "ficus_unified_v6-20260416-014135"),
            "Hotdog": os.path.join(LOG, "hotdog_unified_v6-20260416-040838"),
            "Lego":   os.path.join(LOG, "lego_unified_v6-20260416-062047"),
        },
    }
    print("\n% ── Table 4.3: Albedo reconstruction ──────────────────────")
    print("% Method & Ficus PSNR±std & SSIM±std & LPIPS±std & Hotdog ... & Lego ...")
    for key, scene_dirs in scene_map.items():
        label = "TensoIR (local repro.)" if key == "repro" else "Unified Curriculum Pipeline"
        cells = []
        for scene in ["Ficus", "Hotdog", "Lego"]:
            d = load_npz(scene_dirs[scene])
            if d is not None:
                pm, ps = ms(d["psnr_alb_single"]) if "psnr_alb_single" in d else (0, 0)
                sm, ss = ms(d["ssim_alb_single"])  if "ssim_alb_single"  in d else (0, 0)
                lm, ls = ms(d["lpips_vgg_alb_single"]) if "lpips_vgg_alb_single" in d else (0, 0)
                cells += [f"${fmt(pm, ps)}$", f"${fmt4(sm, ss)}$", f"${fmt4(lm, ls)}$"]
            else:
                cells += ["---", "---", "---"]
        print(f"{label} & Rot.\\ multi & {' & '.join(cells)} \\\\")


# ─────────────────────────────────────────────────────────────────────────────
# Table 4.5 — NVS quality (RF + PBR)
# ─────────────────────────────────────────────────────────────────────────────

def table_45():
    scene_map = {
        "repro": {
            "Ficus":  os.path.join(LOG, "ficus_vanilla_rotated_baseline-20260409-102551"),
            "Hotdog": os.path.join(LOG, "hotdog_vanilla_rotated_baseline-20260409-104734"),
            "Lego":   os.path.join(LOG, "lego_vanilla_rotated_baseline-20260409-121707"),
        },
        "unified": {
            "Ficus":  os.path.join(LOG, "ficus_unified_v6-20260416-014135"),
            "Hotdog": os.path.join(LOG, "hotdog_unified_v6-20260416-040838"),
            "Lego":   os.path.join(LOG, "lego_unified_v6-20260416-062047"),
        },
    }
    print("\n% ── Table 4.5: NVS quality ──────────────────────────────────")
    for render, psnr_key, ssim_key, lpips_key in [
        ("RF",  "psnr_nvs",  "ssim_nvs",  "lpips_vgg_nvs"),
        ("PBR", "psnr_brdf", "ssim_brdf", "lpips_vgg_brdf"),
    ]:
        for key, scene_dirs in scene_map.items():
            label = "TensoIR (local repro.)" if key == "repro" else "Unified Curriculum Pipeline"
            cells = []
            for scene in ["Ficus", "Hotdog", "Lego"]:
                d = load_npz(scene_dirs[scene])
                if d is not None:
                    pm, ps = ms(d[psnr_key])  if psnr_key  in d else (0, 0)
                    sm, ss = ms(d[ssim_key])  if ssim_key  in d else (0, 0)
                    lm, ls = ms(d[lpips_key]) if lpips_key in d else (0, 0)
                    cells += [f"${fmt(pm, ps)}$", f"${fmt4(sm, ss)}$", f"${fmt4(lm, ls)}$"]
                else:
                    cells += ["---", "---", "---"]
            print(f"{render} & {label} & Rot.\\ multi & {' & '.join(cells)} \\\\")


# ─────────────────────────────────────────────────────────────────────────────
# Tables 4.6–4.9 — Relighting
# ─────────────────────────────────────────────────────────────────────────────

RELIGHT_RUNS = {
    "repro": {
        "ficus":  os.path.join(RLIT, "vanilla_ficus"),
        "hotdog": os.path.join(RLIT, "vanilla_hotdog"),
        "lego":   os.path.join(RLIT, "vanilla_lego"),
    },
    "unified": {
        "ficus":  os.path.join(RLIT, "v6_ficus"),
        "hotdog": os.path.join(RLIT, "v6_hotdog"),
        "lego":   os.path.join(RLIT, "v6_lego"),
    },
}


def relight_stats(scene_dir):
    """Returns {env: {metric: (mean, std)}} for all env maps."""
    data = parse_relight_per_view(scene_dir)
    stats = {}
    for env, arrays in data.items():
        stats[env] = {}
        for metric, vals in arrays.items():
            if len(vals) > 0:
                stats[env][metric] = ms(np.asarray(vals, dtype=float))
            else:
                stats[env][metric] = (float("nan"), float("nan"))
    return stats


def table_46():
    """Summary table: mean over 5 env maps ± std across env maps."""
    print("\n% ── Table 4.6: Relighting summary (mean over 5 env maps) ───")
    print("% Metric & Ficus Base & Ficus Ours & Hotdog Base & Hotdog Ours & Lego Base & Lego Ours")
    for metric in ["psnr", "ssim", "lpips_vgg"]:
        cells = []
        for scene in ["ficus", "hotdog", "lego"]:
            for key in ["repro", "unified"]:
                stats = relight_stats(RELIGHT_RUNS[key][scene])
                per_env_means = [stats[e][metric][0] for e in ENV_MAPS if e in stats and metric in stats[e]]
                if per_env_means:
                    m = np.mean(per_env_means)
                    s = np.std(per_env_means, ddof=0)
                    cells.append(f"${fmt(m, s)}$")
                else:
                    cells.append("---")
        print(f"{metric.upper()} & {' & '.join(cells)} \\\\")


def table_47_49():
    """Per-environment tables for each scene.
    Column order: Env | PSNR_base±std | PSNR_ours±std | SSIM_base±std | SSIM_ours±std | LPIPS_base±std | LPIPS_ours±std
    std is across the 200 test views for that env map.
    """
    for scene_name, scene_key in [("Ficus", "ficus"), ("Hotdog", "hotdog"), ("Lego", "lego")]:
        print(f"\n% ── Table per-env: {scene_name} relighting ──────────────────")
        print("% Env & PSNR Base & PSNR Ours & SSIM Base & SSIM Ours & LPIPS Base & LPIPS Ours")
        repro_stats   = relight_stats(RELIGHT_RUNS["repro"][scene_key])
        unified_stats = relight_stats(RELIGHT_RUNS["unified"][scene_key])

        # accumulators for per-env means (used in Average row)
        acc = {m: {"base": [], "ours": []} for m in ["psnr", "ssim", "lpips_vgg"]}

        for env in ENV_MAPS:
            row_cells = [env.capitalize()]
            # For each metric, emit Base then Ours (interleaved)
            for metric in ["psnr", "ssim", "lpips_vgg"]:
                for key, stats in [("base", repro_stats), ("ours", unified_stats)]:
                    if env in stats and metric in stats[env]:
                        m, s = stats[env][metric]
                        acc[metric][key].append(m)
                        d = 2 if metric == "psnr" else 4
                        row_cells.append(f"${fmt(m, s, decimals=d)}$")
                    else:
                        row_cells.append("---")
            print(" & ".join(row_cells) + " \\\\")

        # Average row: mean of the 5 per-env means ± std across env maps
        print("\\midrule")
        avg_cells = ["\\textbf{Average}"]
        for metric in ["psnr", "ssim", "lpips_vgg"]:
            for key in ["base", "ours"]:
                vals = acc[metric][key]
                if vals:
                    m = np.mean(vals); s = np.std(vals, ddof=0)
                    d = 2 if metric == "psnr" else 4
                    avg_cells.append(f"$\\mathbf{{{fmt(m, s, decimals=d)}}}$"
                                     if key == "base" else f"${fmt(m, s, decimals=d)}$")
                else:
                    avg_cells.append("---")
        print(" & ".join(avg_cells) + " \\\\")


# ─────────────────────────────────────────────────────────────────────────────
# Table 4.10 — Curriculum ablation
# ─────────────────────────────────────────────────────────────────────────────

ABLATION_RUNS = {
    "v1":  [os.path.join(LOG, "ficus_unified_v1-20260415-100212")],
    "v2a": [os.path.join(LOG, "ficus_unified_v2-20260415-112522")],
    "v2b": [os.path.join(LOG, "ficus_unified_v2-20260415-112640")],
    "v3a": [os.path.join(LOG, "ficus_unified_v3-20260415-140838")],
    "v3b": [os.path.join(LOG, "ficus_unified_v3-20260415-141349")],
    "v3c": [os.path.join(LOG, "ficus_unified_v3-20260415-141844")],
    "v3d": [os.path.join(LOG, "ficus_unified_v3-20260415-144059")],
    "v4":  [os.path.join(LOG, "ficus_unified_v4-20260415-155536")],
    "v5":  [os.path.join(LOG, "ficus_unified_v5-20260415-234054")],
    "v6":  [os.path.join(LOG, "ficus_unified_v6-20260416-014135")],
}


def table_410():
    print("\n% ── Table 4.10: Curriculum ablation ────────────────────────")
    print("% Ver & PSNR_nvs±std & PSNR_brdf±std & PSNR_alb±std & SSIM_alb±std & LPIPS_alb±std & MAE±std")
    for ver, run_dirs in ABLATION_RUNS.items():
        row_cells = [ver]
        for metric, key in [
            ("PSNR_nvs",  "psnr_nvs"),
            ("PSNR_brdf", "psnr_brdf"),
            ("PSNR_alb",  "psnr_alb_single"),
            ("SSIM_alb",  "ssim_alb_single"),
            ("LPIPS_alb", "lpips_vgg_alb_single"),
            ("MAE",       "mae"),
        ]:
            all_vals = []
            for rdir in run_dirs:
                d = load_npz(rdir)
                if d is not None and key in d:
                    all_vals.append(np.mean(d[key]))
            if all_vals:
                m, s = ms(all_vals) if len(all_vals) > 1 else (all_vals[0], float("nan"))
                row_cells.append(f"${fmt(m, s)}$" if len(all_vals) > 1 else f"${all_vals[0]:.2f}$")
            else:
                row_cells.append("---")
        print(" & ".join(row_cells) + " \\\\")


# ─────────────────────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    print("% ================================================================")
    print("% aggregate_thesis_metrics.py  —  Chapter 4 mean±std table rows")
    print("% Run from TensoIR repo root after scripts/run_primary_reeval.sh")
    print("% ================================================================")

    table_42()
    table_43()
    table_45()
    table_46()
    table_47_49()
    table_410()

    print("\n% ── Verification reminder ──────────────────────────────────────")
    print("% Cross-check: np.mean of any psnr_nvs array should match the")
    print("% corresponding PSNR_nvs value in metrics_record.txt (±0.01 dB).")